service: ViNCnT-DB

provider:
  name: aws
  runtime: nodejs8.10
  region: ${file(../serverless.yml):provider.region}

custom:
  dev:
    deletionPolicy: Delete
  prod:
    deletionPolicy: Retain

resources:
  Resources:
    LocationsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: ${self:custom.${opt:stage, self:provider.stage}.deletionPolicy}
      Properties:
        AttributeDefinitions:
          - AttributeName: City
            AttributeType: S
          - AttributeName: Name
            AttributeType: S
        KeySchema:
          - AttributeName: City
            KeyType: HASH
          - AttributeName: Name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: "${self:service}-locations-${opt:stage, self:provider.stage}"
    UsersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: ${self:custom.${opt:stage, self:provider.stage}.deletionPolicy}
      Properties:
        AttributeDefinitions:
          - AttributeName: Email
            AttributeType: S
        KeySchema:
          - AttributeName: Email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: "${self:service}-users-${opt:stage, self:provider.stage}"
    VotesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: ${self:custom.${opt:stage, self:provider.stage}.deletionPolicy}
      Properties:
        AttributeDefinitions:
          - AttributeName: Session
            AttributeType: S
          - AttributeName: Email
            AttributeType: S
        KeySchema:
          - AttributeName: Session
            KeyType: HASH
          - AttributeName: Email
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: "${self:service}-votes-${opt:stage, self:provider.stage}"
    RestaurantsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: ${self:custom.${opt:stage, self:provider.stage}.deletionPolicy}
      Properties:
        AttributeDefinitions:
          - AttributeName: Name
            AttributeType: S
        KeySchema:
          - AttributeName: Name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: "${self:service}-restaurants-${opt:stage, self:provider.stage}"
    SessionsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: ${self:custom.${opt:stage, self:provider.stage}.deletionPolicy}
      Properties:
        AttributeDefinitions:
          - AttributeName: City
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: City
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: "${self:service}-sessions-${opt:stage, self:provider.stage}"
